// Copyright (C) 2018 The Mypher Authors
//
// SPDX-License-Identifier: LGPL-3.0+
//

#ifndef COMMON_MESSAGEID_H
#define COMMON_MESSAGEID_H

#define NOT_FOUND 1
#define INVALID_PARAM 2
#define ALREADY_FORMAL 3
#define SENDER_CANT_EDIT 4
#define SENDER_NOT_APPROVER 5
#define SENDER_ALREADY_APPROVE 6
#define SENDER_NOT_APPROVE_YET 7
#define TOKEN_ALREADY_ISSUED 8
#define INSUFFICIENT_AMOUNT 9
#define TOKEN_NOT_OWNED_BY_SENDER 10
#define INVALID_RECIPIENT 11
#define NOT_FULFILL_REQUIREMENT 12
#define PIC_NOT_ASSIGNED 13
#define RESULTS_IN_REVIEW 14
#define PIC_NOT_APPROVED 15
#define TASK_COMPLETED 16
#define PIC_IS_ASSIGNED 17
#define PIC_IS_NOT_SENDER 18
#define INVALID_REWARD 19
#define INCONSISTENT_DATA_EXISTS 20
#define NOT_IMPLEMENT_YET 99999

#endif // COMMON_MESSAGEID_H