// Copyright (C) 2018 The Mypher Authors
//
// SPDX-License-Identifier: LGPL-3.0+
//

#ifndef COMMON_MESSAGEID_H
#define COMMON_MESSAGEID_H

#define NOT_FOUND 1
#define ALREADY_REGISTERED 2
#define INVALID_VERSION 3
#define ALREADY_FORMAL 4
#define SENDER_CANT_EDIT 5
#define SENDER_NOT_APPROVER 6
#define SENDER_ALREADY_APPROVED 7
#define SENDER_NOT_APPROVE_YET 8
#define NOT_IMPLEMENT_YET 9
#define NOT_EDITABLE 10
#define PIC_IS_ASSIGNED 11
#define CIPHER_NOT_FOUND 12
#define NAME_TOO_SHORT 13
#define INVALID_AUTHORIZORS 14
#define INVALID_PIC 15

#endif // COMMON_MESSAGEID_H