// Copyright (C) 2018 The Mypher Authors
//
// SPDX-License-Identifier: LGPL-3.0+
//

#ifndef COMMON_MESSAGEID_H
#define COMMON_MESSAGEID_H

#define NOT_FOUND 1
#define ALREADY_REGISTERED 2
#define INVALID_VERSION 3
#define ALREADY_FORMAL 4
#define SENDER_CANT_EDIT 5
#define SENDER_NOT_APPROVER 6
#define SENDER_ALREADY_APPROVE 7
#define SENDER_NOT_APPROVE_YET 8
#define NOT_IMPLEMENT_YET 9
#define NOT_EDITABLE 10
#define PIC_IS_ASSIGNED 11
#define CIPHER_NOT_FOUND 12
#define NAME_TOO_SHORT 13
#define INVALID_APPROVER 14
#define INVALID_PIC 15
#define TASK_OWNED_BY_CIPHER 16
#define PIC_ALREADY_APPROVED 17
#define PIC_IS_NOT_SENDER 18
#define PIC_NOT_ASSIGNED 19
#define TASK_ALREADY_APPROVED 20
#define RESULTS_ALREADY_APPROVED 21
#define TASK_NOT_APPROVED 22
#define RESULTS_APPROVED_SOME 23
#define PIC_NOT_APPROVED 24
#define INVALID_TOKENID 25
#define TOKEN_NOT_OWNED_BY_SENDER 26
#define INVALID_REWARD 27
#define CIPHER_NOT_DRAFT 28
#define INVALID_TASK 29
#define INVALID_TOKEN 30
#define APPROVER_NOT_SET 31
#define INVALID_ISSUER 32
#define INSUFFICIENT_AMOUNT 33
#define INVALID_RECEIVER 34
#define TOKEN_ALREADY_ISSUED 35
#define NOT_FULFILL_REQUIREMENT 36 

#endif // COMMON_MESSAGEID_H